---
- name: Update and Upgrade APT
  hosts: ubuntu
  become: true
  tasks:

  - name: Update APT cache
    apt: 
     update_cache: yes
     cache_valid_time: 86400 #One day
  - name: Upgrade APT
    apt:
     upgrade: yes
